### ISSUE TITLE
Not possible to send keyed Avro messages via Proxy

### ISSUE THREAD

**Issue by martin-voigt** [confluentinc/kafka-rest#118] opened 2015-10-20 13:07 UTC
We tried different ways, like curl or [kafka-node-rest](https://github.com/confluentinc/kafka-rest-node), to send a Avro message to a topic with a key. The topic is created and schema submitted to schema registry, however, sending the message fails with a HTTP error code 500. Setting like ports etc. are all defaults for the platform.

Here an example what we tried with kafka-node-rest:

* create the schemata for key and value

```javascript
var idSchema = new KafkaRest.AvroSchema('string');
var valueSchema = new KafkaRest.AvroSchema(
{
	'namespace': 'mynamespace',
	'type': 'record',
	'name': 'myschema',
	'fields':
	[
		{ 'name': 'key',	'type': 'string' },
		{ 'name': 'date',	'type': 'string' },
		{ 'name': 'title',	'type': 'string' }
	]
});
```
* send it

```javascript
topic.produce(idSchema, valueSchema,
	{
		'key': link,
		'value':
		{
			'key': link,
			'date': date,
			'title': title
		}
	},
	function(err, res) { ... });
```
what throws an error.
```javascript
{
	name: 'APIError',
    status: 500,
    message: 'Internal Server Error',
    data:
	{
		error_code: 500,
		message: 'Internal Server Error'
	}
}
```
* sending without a key works
```javascript
topic.produce(valueSchema,
	{
		'key': link,
		'date': date,
		'title': title
	},
	function(err, res) { ... });
```
result:
```javascript
{
	offsets: [ { partition: 0, offset: 750, error_code: null, error: null } ],
    key_schema_id: null,
    value_schema_id: 121
}
```

However, with the **kafka-avro-console-producer** works fine

```shell
./bin/kafka-avro-console-producer --broker-list localhost:9092 --topic rss \
  --property parse.key=true \
  --property key.separator=, \
  --property key.schema='{"type":"string"}' \
  --property value.schema="{\"type\": \"record\", \"name\": \"rss\", \"fields\": [{\"name\": \"key\", \"type\": \"string\"}, {\"name\": \"title\", \"type\": \"string\"}, {\"name\": \"content\", \"type\": \"string\"}, {\"name\": \"date\", \"type\": \"string\"}]}"

"test",{"key": "http://example.com", "title": "test title", "content": "test content", "date": "2015-10-18'T'20:20:20"}
```

Any idea what could be wrong? Maybe this issue relates to [#114](https://github.com/confluentinc/kafka-rest/issues/114). Thanks in advance.

**Comment by atridgedcosta** [comment] 2016-01-11 05:32
:+1:

**Comment by gfodor** [comment] 2016-02-18 07:11
:+1: Yes, it seems that this exception occurs if you try to use a string key schema. Int keys work fine.

**Comment by allcentury** [comment] 2016-02-18 19:37
We're also seeing the same thing and easy to reproduce with the curl requests:

success with an `int` key:

```
 curl -X POST -H "Content-Type: application/vnd.kafka.avro.v1+json" \
      --data '{"key_schema": "{\"type\": \"int\"}", "value_schema": "{\"type\": \"record\", \"name\": \"User\", \"fields\": [{\"name\": \"name\", \"type\": \"string\"}]}", "records": [{"value": {"name": "testUser"}, "key": 123}]}' \
      "http://$DOCKER_IP:8082/topics/avrotest"
{"offsets":

[{"partition":0,"offset":0,"error_code":null,"error":null}],"key_schema_id":46,"value_schema_id":47}
```

Failure with a string:

```
curl -X POST -H "Content-Type: application/vnd.kafka.avro.v1+json" \
      --data '{"key_schema": "{\"type\": \"string\"}", "value_schema": "{\"type\": \"record\", \"name\": \"User\", \"fields\": [{\"name\": \"name\", \"type\": \"string\"}]}", "records": [{"value": {"name": "testUser"}, "key": "abcd"}]}' \
      "http://$DOCKER_IP:8082/topics/avrotest2"

{"error_code":500,"message":"Internal Server Error"}%
```

**Comment by luinix** [comment] 2016-03-01 11:46
I'm currently suffering this bug in my project :disappointed: Is there any estimation of when will this get solved?

**Comment by luinix** [comment] 2016-03-02 18:15
I found the issue and proposed a fix in this PR: https://github.com/confluentinc/kafka-rest/pull/165

**Comment by luinix** [comment] 2016-03-11 11:31
This has been fixed in confluentinc/schema-registry/pull/297, but I don't have an idea of when the next version including this fix will be released.

**Closed** 2016-03-11 16:27 UTC

**Comment by 0xABAB** [comment] 2016-04-13 14:05
Why are you closing an issue when it has not been fixed in a released version?

**Comment by ewencp** [comment] 2016-04-13 15:14
@0xABAB Because that's the way we normally track bugs and their fixes. This is how many open source projects, including Kafka, also track issues. If we didn't close bugs when they get fixed, each release would be accompanied by digging through old issues for ones that have been fixed and a flurry of notifications as we close a bunch of bugs. Additionally, since all this code is open source, marking it as closed is a useful indicator to anyone that comes across the bug that if they need to get the fix, they can build from master (or backport the patch).
