### ISSUE TITLE
Consumer read takes long time with multiple consumers in consumer group

### ISSUE THREAD

**Issue by PlatEng** [confluentinc/kafka-rest#341] opened 2017-09-14 14:04 UTC
A fundamental issue is seen with REST Proxy. Suppose if we create two consumer instances under the same consumer group, read call is taking longer time with calls with subsequent instance.

Steps to reproduce:
1. Create my_consumer_instance1 and my_consumer_instance2 under my_json_consumer1:
curl -H "Content-Type: application/vnd.kafka.v2+json" -d '{"name": "my_consumer_instance1", "format": "json", "auto.offset.reset": "earliest"}' http://localhost:8082/consumers/my_json_consumer1
curl -H "Content-Type: application/vnd.kafka.v2+json" -d '{"name": "my_consumer_instance2", "format": "json", "auto.offset.reset": "earliest"}' http://localhost:8082/consumers/my_json_consumer1

2. Subscribe both the instances to topic test1:
curl -H "Content-Type: application/vnd.kafka.v2+json" -d '{"topics":["test1"]}' http://localhost:8082/consumers/my_json_consumer1/instances/my_consumer_instance1/subscription
curl -H "Content-Type: application/vnd.kafka.v2+json" -d '{"topics":["test1"]}' http://localhost:8082/consumers/my_json_consumer1/instances/my_consumer_instance2/subscription

3. Read the message from my_consumer_instance1 several times and we will get responses back:
curl -X GET -H "Accept: application/vnd.kafka.json.v2+json" http://localhost:8082/consumers/my_json_consumer1/instances/my_consumer_instance1/records

4. Read the message from my_consumer_instance2 and the call will hang. It will take around 8 minutes to get a response back:
curl -X GET -H "Accept: application/vnd.kafka.json.v2+json" http://localhost:8082/consumers/my_json_consumer1/instances/my_consumer_instance2/records

5. Again read the message from my_consumer_instance1 and the call will hang. It will take some time to get a response back:
curl -X GET -H "Accept: application/vnd.kafka.json.v2+json" http://localhost:8082/consumers/my_json_consumer1/instances/my_consumer_instance1/records

**Comment by ZachTB123** [comment] 2017-11-20 16:22
Any updates on this?

**Comment by woodlee** [comment] 2018-02-27 23:27
See my comment over on https://github.com/confluentinc/kafka-rest/issues/396

**Comment by tPl0ch** [comment] 2018-08-15 17:43
This is pretty much happening for all our teams using the REST proxy. So everyone is only able to run a single consumer within a group currently and this defies all advantages you want to have.

**Comment by fkaufer** [comment] 2018-08-28 19:50
@mageshn Can you explain why you removed the "bug" label from this issue? The workaround described on #396 doesn't really work robustly in our case and even if it would, it requires a lot of (brittle) orchestration / config management around the REST Proxy. The issue is easy to reproduce and the impact is severe. We will probably soon remove the REST Proxy entirely from our stack because of this.

**Comment by Sevavietl** [comment] 2018-09-26 12:41
Although the library is a convenient concept for those using languages without decent native Kafka client (in my case PHP), it is indeed unusable due to the limit of one consumer per group.

With workaround described on [#396](https://github.com/confluentinc/kafka-rest/issues/396) I, myself, getting the following exception: `KafkaConsumer is not safe for multi-threaded access`. So it will get you nowhere.

It would be nice to get any comments about this from the mainteiners. It is a nice lib. I am willing to use it (even wrote PHP client for it), but in present state I do not see any applications of it, except really simple producing and reading.

Thank you in advance.

**Comment by douglarek** [comment] 2018-09-27 10:16
A horrible bug needs fixing

**Comment by ehumber** [comment] 2022-04-14 11:22
This should be fixed by https://github.com/confluentinc/kafka-rest/pull/942

Closing this issue. 

Please reopen/raise a new issue if the problem is still seen after this change.

**Closed by ehumber** 2022-04-14 11:22 UTC
