### ISSUE TITLE
neither `enable.auto.commit` or `auto.commit.enable` working

### ISSUE THREAD

**Issue by lironess** [confluentinc/kafka-rest#161] opened 2016-02-14 15:55 UTC
Hi.
I'm using confluent 2.0 and kafka 0.9.
I've seen the documentation [here](http://kafka.apache.org/documentation.html#consumerconfigs).
I tried to make an consumer group and instance their offset will be commited manually.
I did so:
```bash
curl -X POST -H "Content-Type: application/vnd.kafka.v1+json" --data '{"name": "myconsumer15", "format": "json", "auto.commit.enable": "false"}' localhost:8000/kafka-rest-proxy/consumers/myconsumer15
```
and got 200 with the url to the instance. tried it also for other groups with enable.auto.commit, and put the boolean on string and boolean (1st with boolean, 1st with string, 2nd with boolean, 2nd with string)

When I tried to cosume with `enable.auto.commit` it said `"Unrecognized field: enable.auto.commit"}`.

When I consumed with:
```bash
curl -X GET -H "Accept: application/vnd.kafka.json.v1+json" http://localhost:8000/kafka-rest-proxy/consumers/myconsumer15/instances/myconsumer15/topics/test5
```
i got a message i produced. When I did that request again, i was expecting to get it again - because i have'nt commited the offset manually, but it passed to the next message.

Any solution ?

**Comment by ewencp** [comment] 2016-02-14 16:56
@lironess Did you create a new consumer instance again and then read from that one? If you read from one consumer instance, it will read the messages in order, each one time. This is the normal behavior for consumer instances. You would only expect to see the same message repeated if you created a new instance after destroying the last one (or letting it expire such that it is cleaned up automatically).

**Comment by lironess** [comment] 2016-02-15 09:18
No. I'll list all the orders:
```
curl -X POST -H "Content-Type: application/vnd.kafka.v1+json" --data '{"name": "myconsumer15", "format": "json", "auto.commit.enable": "false"}' localhost:8000/kafka-rest-proxy/consumers/myconsumer15

curl -X POST -H "Content-Type: application/vnd.kafka.v1+json" --data '{"name": "myconsumer16", "format": "json", "auto.commit.enable": false}' localhost:8000/kafka-rest-proxy/consumers/myconsumer16

curl -X POST -H "Content-Type: application/vnd.kafka.v1+json" --data '{"name": "myconsumer17", "format": "json", "enable.auto.commit": "false"}' localhost:8000/kafka-rest-proxy/consumers/myconsumer17

curl -X POST -H "Content-Type: application/vnd.kafka.v1+json" --data '{"name": "myconsumer18", "format": "json", "enable.auto.commit": false}' localhost:8000/kafka-rest-proxy/consumers/myconsumer18
```

3rd and 4th commands returned `"Unrecognized field: enable.auto.commit"`
1st and 2nd - tried to consume twice, but second call to each one returned empty array instead of the message i produced. (first call returned it, but i was expecting the second time to return it too because i told it to not commit offset)

**Comment by ewencp** [comment] 2016-02-16 03:32
@lironess The `enable.auto.commit` is not a valid option, so the second two shouldn't work.

For the first two, it looks like you've created two separate consumer groups. It may be confusing because you've used `myconsumer15` and `myconsumer16` as both the *consumer group ID* (the last segment in the URL in the curl commands you gave) and the *consumer instance name*. If you:

1. Create `myconsumer15`
2. Create `myconsumer16`
3. Produce a message
4. Consume from `myconsumer15`
5. Consume from `myconsumer16`

Then you should expect to see both consume the message. On the other hand, it sounds like you could possibly be doing something like this order:

1. Create `myconsumer15`
2. Produce a message
3. Consume from `myconsumer15`
4. Create `myconsumer16`
5. Consume from `myconsumer16`

Then `myconsumer16` would not return any data. This is because by default it will start at the latest offset and the message was produced before `myconsumer16` existed.

If this isn't the sequence of events, can you list the complete set of curl commands (both creating consumers, destroying them if relevant, and consuming data), and include the amount of time between requests? Without a complete sequence of operations, it's difficult to tell why you may be seeing the behavior you are, or reproduce it to debug it.

**Comment by lironess** [comment] 2016-02-16 09:37
So what i was talking about is that situation:
1. create a test topic
2. Produce a message to test topic
3. Create myconsumer15
4. Consume from myconsumer15 (the response: first message)
5. Consume from myconsumer15 (the response: empty array, which means the offset where moving)

I was expecting in step 5 that the consumer will not commit its offset if I didn't told it too. What i think is happening that I didn't get the real meaning of offset. I was thinking that it means the point to read from kafka, while the behavior shows me thats its the point to start read from if the consumer if it was shut down.

I'll tell you what is the scenario that I'm trying to solve, maybe you can give me number of commands to do so.
Right now I'm using [Node.js client for the Kafka REST proxy](https://github.com/confluentinc/kafka-rest-node) but it doesn't that matter, I just want to get the concept right.
Im consuming messages from Kafka by joining a consumer group and subscribing to it. If the Node.js process fails, the consumer should be shut down. When the process is up again, it should keep reading from the point it was stopped. Right now when I stop and restart the application the consumer don't subscribe a thing for some minutes, and then consumes everything from the beginning of time. So I wanted to control somehow the offset (maybe without that driver, but with http) and then got to this problem.

**Comment by ewencp** [comment] 2016-02-16 14:17
@lironess The behavior you're looking for is handled by offset commit. Offset commits are for persistent storage of the current position of a consumer group so that even if all of the consumer instances in the group shut down, they will resume from the last committed offset.

Kafka won't write these offsets every time you consume data, you have to explicitly request for the offset to be committed. This means that in the case of a crash, you may see a few messages repeated (the ones after the last time the offsets were committed).

You seem to have the basic model down now. In terms of using the REST API, you'll just want to make sure your application [commits offsets](http://docs.confluent.io/2.0.0/kafka-rest/docs/api.html#post--consumers-%28string-group_name%29-instances-%28string-instance%29-offsets) periodically. It's up to you to choose how frequently (or turn on auto commit, although since that option can commit as soon as the data is returned, you can accidentally lose data if auto commit runs before data has been processed -- use at your own risk).

**Closed** 2016-02-16 14:28 UTC

**Comment by ujlbu4** [comment] 2017-11-10 22:32
Hi, @ewencp 

according to your [first answer](https://github.com/confluentinc/kafka-rest/issues/161#issuecomment-183923725) in this topic, if I will create second consumer-instance after destroy first one (in the same consumer-group) then i should received the same messages
but i checked and it didn't :(

Here is log of requests for reproduce:
```
[create first consumer]: 
    curl -i -X POST -H "User-Agent: python-requests/2.18.1" -H "Accept: application/vnd.kafka.json.v2+json,application/vnd.kafka+json,application/json" -H "Connection: keep-alive" -H "Content-Type: application/vnd.kafka.json.v2+json" -d '{"name": "instance-2dafc681e0614fe580ef6e3c5c1bec56", "format": "json", "auto.offset.reset": "latest", "auto.commit.enable": false}' 'http://localhost:8082/consumers/group-1a7b5e2100a447d9baf4db693fe53121'
    [response code]: 
    200

    [response headers]: 
    {'Date': 'Fri, 10 Nov 2017 22:24:11 GMT', 'Content-Type': 'application/vnd.kafka.json.v2+json', 'Content-Length': '195', 'Server': 'Jetty(9.2.19.v20160908)'}

    [response text]: 
    {"instance_id":"instance-2dafc681e0614fe580ef6e3c5c1bec56","base_uri":"http://localhost:8082/consumers/group-1a7b5e2100a447d9baf4db693fe53121/instances/instance-2dafc681e0614fe580ef6e3c5c1bec56"}


[first consumer subscribe]: 
    curl -i -X POST -H "User-Agent: python-requests/2.18.1" -H "Accept: application/vnd.kafka.json.v2+json,application/vnd.kafka+json,application/json" -H "Connection: keep-alive" -H "Content-Type: application/vnd.kafka.json.v2+json" -d '{"topics": ["test-kafka-autotests"]}' 'http://localhost:8082/consumers/group-1a7b5e2100a447d9baf4db693fe53121/instances/instance-2dafc681e0614fe580ef6e3c5c1bec56/subscription'
    [response code]: 
    204

    [response headers]: 
    {'Date': 'Fri, 10 Nov 2017 22:24:11 GMT', 'Server': 'Jetty(9.2.19.v20160908)'}

    [response text]: 
    

[first consumer records]: 
    curl -i -X GET -H "User-Agent: python-requests/2.18.1" -H "Accept: application/vnd.kafka.json.v2+json,application/vnd.kafka+json,application/json" -H "Connection: keep-alive" -H "Content-Type: application/vnd.kafka.json.v2+json" -d '' 'http://localhost:8082/consumers/group-1a7b5e2100a447d9baf4db693fe53121/instances/instance-2dafc681e0614fe580ef6e3c5c1bec56/records'
    [response code]: 
    200

    [response headers]: 
    {'Date': 'Fri, 10 Nov 2017 22:24:11 GMT', 'Content-Type': 'application/vnd.kafka.json.v2+json', 'Content-Length': '2', 'Server': 'Jetty(9.2.19.v20160908)'}

    [response text]: 
    []


[producer produce record]: 
    curl -i -X POST -H "User-Agent: python-requests/2.18.1" -H "Accept: application/vnd.kafka.json.v2+json,application/vnd.kafka+json,application/json" -H "Connection: keep-alive" -H "Content-Type: application/vnd.kafka.json.v2+json" -d '{"records": [{"value": {"event_type": "blalb", "extra": {"versin": 1, "generated": "e892ad28104d440c8adff00f4b205393"}}, "key": null, "partition": null}]}' 'http://localhost:8082/topics/test-kafka-autotests'
    [response code]: 
    200

    [response headers]: 
    {'Date': 'Fri, 10 Nov 2017 22:24:12 GMT', 'Content-Type': 'application/vnd.kafka+json', 'Content-Length': '116', 'Server': 'Jetty(9.2.19.v20160908)'}

    [response text]: 
    {"offsets":[{"partition":0,"offset":27,"error_code":null,"error":null}],"key_schema_id":null,"value_schema_id":null}


[first consumer records]: 
    curl -i -X GET -H "User-Agent: python-requests/2.18.1" -H "Accept: application/vnd.kafka.json.v2+json,application/vnd.kafka+json,application/json" -H "Connection: keep-alive" -H "Content-Type: application/vnd.kafka.json.v2+json" -d '' 'http://localhost:8082/consumers/group-1a7b5e2100a447d9baf4db693fe53121/instances/instance-2dafc681e0614fe580ef6e3c5c1bec56/records'
    [response code]: 
    200

    [response headers]: 
    {'Date': 'Fri, 10 Nov 2017 22:24:12 GMT', 'Content-Type': 'application/vnd.kafka.json.v2+json', 'Content-Length': '170', 'Server': 'Jetty(9.2.19.v20160908)'}

    [response text]: 
    [{"topic":"test-kafka-autotests","key":null,"value":{"event_type":"blalb","extra":{"versin":1,"generated":"e892ad28104d440c8adff00f4b205393"}},"partition":0,"offset":27}]


[destroy first consumer]: 
    curl -i -X DELETE -H "User-Agent: python-requests/2.18.1" -H "Accept: application/vnd.kafka.json.v2+json,application/vnd.kafka+json,application/json" -H "Connection: keep-alive" -H "Content-Type: application/vnd.kafka.json.v2+json" -d '' 'http://localhost:8082/consumers/group-1a7b5e2100a447d9baf4db693fe53121/instances/instance-2dafc681e0614fe580ef6e3c5c1bec56'
    [response code]: 
    204

    [response headers]: 
    {'Date': 'Fri, 10 Nov 2017 22:24:13 GMT', 'Server': 'Jetty(9.2.19.v20160908)'}

    [response text]: 
    

[create second consumer (same consumer-group)]: 
    curl -i -X POST -H "User-Agent: python-requests/2.18.1" -H "Accept: application/vnd.kafka.json.v2+json,application/vnd.kafka+json,application/json" -H "Connection: keep-alive" -H "Content-Type: application/vnd.kafka.json.v2+json" -d '{"name": "instance-0946bb1542604424a395512530e9c414", "format": "json", "auto.offset.reset": "latest", "auto.commit.enable": false}' 'http://localhost:8082/consumers/group-1a7b5e2100a447d9baf4db693fe53121'
    [response code]: 
    200

    [response headers]: 
    {'Date': 'Fri, 10 Nov 2017 22:24:13 GMT', 'Content-Type': 'application/vnd.kafka.json.v2+json', 'Content-Length': '195', 'Server': 'Jetty(9.2.19.v20160908)'}

    [response text]: 
    {"instance_id":"instance-0946bb1542604424a395512530e9c414","base_uri":"http://localhost:8082/consumers/group-1a7b5e2100a447d9baf4db693fe53121/instances/instance-0946bb1542604424a395512530e9c414"}


[subscribe second consumer]: 
    curl -i -X POST -H "User-Agent: python-requests/2.18.1" -H "Accept: application/vnd.kafka.json.v2+json,application/vnd.kafka+json,application/json" -H "Connection: keep-alive" -H "Content-Type: application/vnd.kafka.json.v2+json" -d '{"topics": ["test-kafka-autotests"]}' 'http://localhost:8082/consumers/group-1a7b5e2100a447d9baf4db693fe53121/instances/instance-0946bb1542604424a395512530e9c414/subscription'
    [response code]: 
    204

    [response headers]: 
    {'Date': 'Fri, 10 Nov 2017 22:24:13 GMT', 'Server': 'Jetty(9.2.19.v20160908)'}

    [response text]: 
    

[second consumer records]: 
    curl -i -X GET -H "User-Agent: python-requests/2.18.1" -H "Accept: application/vnd.kafka.json.v2+json,application/vnd.kafka+json,application/json" -H "Connection: keep-alive" -H "Content-Type: application/vnd.kafka.json.v2+json" -d '' 'http://localhost:8082/consumers/group-1a7b5e2100a447d9baf4db693fe53121/instances/instance-0946bb1542604424a395512530e9c414/records'
    [response code]: 
    200

    [response headers]: 
    {'Date': 'Fri, 10 Nov 2017 22:24:13 GMT', 'Content-Type': 'application/vnd.kafka.json.v2+json', 'Content-Length': '2', 'Server': 'Jetty(9.2.19.v20160908)'}

    [response text]: 
    []


[second consumer records]: 
    curl -i -X GET -H "User-Agent: python-requests/2.18.1" -H "Accept: application/vnd.kafka.json.v2+json,application/vnd.kafka+json,application/json" -H "Connection: keep-alive" -H "Content-Type: application/vnd.kafka.json.v2+json" -d '' 'http://localhost:8082/consumers/group-1a7b5e2100a447d9baf4db693fe53121/instances/instance-0946bb1542604424a395512530e9c414/records'
    [response code]: 
    200

    [response headers]: 
    {'Date': 'Fri, 10 Nov 2017 22:24:14 GMT', 'Content-Type': 'application/vnd.kafka.json.v2+json', 'Content-Length': '2', 'Server': 'Jetty(9.2.19.v20160908)'}

    [response text]: 
    []
```
— so there are no records in second consumer :(..

Could you tell where is the mistake? and how to receive the same records?

Thanks!

**Comment by ewencp** [comment] 2017-11-10 23:32
@ujlbu4 You have `"auto.offset.reset": "latest"` so when you create the second consumer and it finds no offsets committed, it uses that policy. That policy does not re-consume old records, it resets the offset to the most recent method and so only sees new messages that are written after the consumer subscribes. If you want to see old messages use `"auto.offset.reset": "earliest"`
