### ISSUE TITLE
api V2 returned empty for GET /consumers/myconsumer/instances/myinstance/records 

### ISSUE THREAD

**Issue by cnwme** [confluentinc/kafka-rest#725] opened 2020-07-29 14:13 UTC
Hi all
Using api v2 kafka-rest, we are facing this bizarre empty response on calling GET  /consumers/myconsumer/instances/myinstance/records, we need to call x2 and some times x5 to get the records from topic.

this issue was detected on old version 3.x.x, and now on 5.4.2.

**Comment by MarkC0x** [comment] 2020-07-29 22:14
Hi @cnwme,

There isn't a lot to go on here, do you have a link to the previous issue you mentioned?

Unless there is a stack-trace available from REST Proxy indicating something is wrong, the fact that no messages are returned usually indicates that the messages are not available to be consumed yet.  Can you, for example, consumer the messages using `kafka-console-consumer` (to ensure they are available), but then using RP it returns nothing?

Another thought is if you can share all the commands you are using to produce and consumer messages?

Cheers
Mark

**Comment by cnwme** [comment] 2020-07-30 06:47
Hi @MarkC0x,
i'll try with debug level on kafka-rest-proxy today.
Yes i confirm that in parallel, consumer native get records directly from topic, and for rest-proxy we must do at least x2 calls to get non empty result.

**Comment by cnwme** [comment] 2020-07-30 10:37
hi @MarkC0x,
here is steps calls kafka-rest-proxy : 

1. create instance : POST /consumers/DEBUG/
`{"name": "kafka","format": "json","auto.offset.reset": "earliest","auto.commit.enable": "true"}`

2. subscribe to topic : POST /consumers/DEBUG/instances/instance1/subscription
`{"topics": ["topic1"]}`

3. start consuming records : GET /consumers/DEBUG/instances/instance1/records
 on this step, we made all time x2 calls to get records , and some times more then x2.
**1st call  (logs kafka-rest-proxy)** : empty response
`[2020-07-30 10:23:36,079] INFO [Consumer clientId=consumer-DEBUG-395898, groupId=DEBUG] Cluster ID: z8alwbaLTMGGG-avJit9JQ (org.apache.kafka.clients.Metadata)
[2020-07-30 10:23:36,081] INFO [Consumer clientId=consumer-DEBUG-395898, groupId=DEBUG] Discovered group coordinator kafka2:9092 (id: 2147483645 rack: null) (org.apache.
kafka.clients.consumer.internals.AbstractCoordinator)
[2020-07-30 10:23:36,093] INFO [Consumer clientId=consumer-DEBUG-395898, groupId=DEBUG] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-07-30 10:23:36,095] INFO [Consumer clientId=consumer-DEBUG-395898, groupId=DEBUG] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-07-30 10:23:39,097] INFO [Consumer clientId=consumer-DEBUG-395898, groupId=DEBUG] Finished assignment for group at generation 3: {consumer-DEBUG-395898-207471fb-646c-4179-ae87-6
2850d11998b=Assignment(partitions=[topic-0, topic-1, topic-2])} (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2020-07-30 10:23:39,110] INFO [Consumer clientId=consumer-DEBUG-395898, groupId=DEBUG] Successfully joined group with generation 3 (org.apache.kafka.clients.consumer.internals.AbstractCoord
inator)
[2020-07-30 10:23:39,111] INFO [Consumer clientId=consumer-DEBUG-395898, groupId=DEBUG] Adding newly assigned partitions: topic-1, topic-2, topic-0 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2020-07-30 10:23:39,112] INFO [Consumer clientId=consumer-DEBUG-395898, groupId=DEBUG] Setting offset for partition topic-1 to the committed offset FetchPosition{of
fset=3900, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=kafka2:9092 (id: 2 rack: null), epoch=28}} (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2020-07-30 10:23:39,112] INFO [Consumer clientId=consumer-DEBUG-395898, groupId=DEBUG] Setting offset for partition topic-2 to the committed offset FetchPosition{of
fset=3976, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=kafka3:9092 (id: 3 rack: null), epoch=29}} (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2020-07-30 10:23:39,112] INFO [Consumer clientId=consumer-DEBUG-395898, groupId=DEBUG] Setting offset for partition topic-0 to the committed offset FetchPosition{of
fset=3899, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=kafka1:9092 (id: 1 rack: null), epoch=31}} (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2020-07-30 10:23:39,113] INFO 172.29.145.84 - - [30/Jul/2020:10:23:36 +0000] "GET /consumers/DEBUG/instances/instance1/records HTTP/1.1" 200 2  3036 (io.confluent.rest-utils.requests)`

**2nd call  :** 
`[2020-07-30 10:24:23,074] INFO 172.29.145.84 - - [30/Jul/2020:10:24:23 +0000] "GET /consumers/DEBUG/instances/instance1/records HTTP/1.1" 200 2593  2 (io.confluent.rest-utils.requests)`
we got some data 
hope that's help to debug
Regards 
Martin

**Comment by MarkC0x** [comment] 2020-07-30 15:57
Hi @cnwme,

Thanks for all the detailed information, I couldn't see anything in the logging which looked out of place, but I did notice that something looked a little strange in your REST Proxy commands.  It may have been a typo when transcribing the requests into this GitHub page, but it looks as though you're creating a consumer instance called "**kafka**" in your initial request, but subsequently referring to the consumer instance as "**instance1**" in the later commands.

I would expect the subscribe request to reply back with the "Consumer instance not found." message though, but just in case something else is happening -- or you have two consumer instances created -- could you try the following:

1. create instance : POST /consumers/DEBUG/
{"name": "kafka","format": "json","auto.offset.reset": "earliest","auto.commit.enable": "true"}

2. subscribe to topic : POST /consumers/DEBUG/instances/**kafka**/subscription
{"topics": ["topic1"]}

3. start consuming records : GET /consumers/DEBUG/instances/**kafka**/records

Could you also check that you don't have another consumer instance created under the name "**instance1**" somewhere please, as that could explain why you were seeing messages arrive at different times than expected.

Cheers
Mark

**Comment by cnwme** [comment] 2020-07-31 08:19
Hi @MarkC0x ,
same result, first call GET /records empty and the second one i get the records. Is-it the normal functionality on kafka-rest-proxy ?
Regards
Martin

**Comment by MarkC0x** [comment] 2020-07-31 15:19
Hi @cnwme,

Thanks for the update.  To answer your question, if there are records available in the topic (i.e. replicated and committed by Kafka), REST Proxy is configured correctly, and the API commands correct, then REST Proxy should retrieve them.

I am currently running REST Proxy 5.4.2 locally using the same commands as we have discussed above and I am unable to reproduce any such behavior you are seeing.

I took another look into your logs though, and another thing jumped out.  The payload you are using to Subscribe to your topic is `{"topics": ["topic1"]}` which means the partitions of "**topic1**".  However, your log is showing a different topic name:

```
[2020-07-30 10:23:39,111] INFO [Consumer clientId=consumer-DEBUG-395898, groupId=DEBUG] Adding newly assigned partitions: topic-1, topic-2, topic-0 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
```

This line is showing the consumer subscribing to partitions `0, 1, and 2` of a topic named "**topic**" (notice the missing "**1**").

When I run the same commands locally, I get the following output which shows the correct topic name "**topic1**" appended with the partitions:

```
[2020-07-31 07:43:37,774] INFO [Consumer clientId=consumer-DEBUG-1, groupId=DEBUG] Adding newly assigned partitions: topic1-1, topic1-0, topic1-2 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:267)
```

I realize this may be frustrating, but could you double check the commands you are running to ensure the topic you are subscribing to is indeed the one you are expecting the data to be present in?

To make this more convenient, let me post the exact-same commands I am using (exported from Postman):

```
curl --location --request POST 'http://localhost:8082/consumers/DEBUG/' --header 'Content-Type: application/vnd.kafka.v2+json' --data-raw '{"name": "kafka","format": "json","auto.offset.reset": "earliest","auto.commit.enable": "true"}'

curl --location --request POST 'http://localhost:8082/consumers/DEBUG/instances/kafka/subscription' --header 'Content-Type: application/vnd.kafka.v2+json' --data-raw '{"topics": ["topic1"]}'

curl --location --request GET 'http://localhost:8082/consumers/DEBUG/instances/kafka/records' --header 'Accept: application/vnd.kafka.json.v2+json' --header 'Content-Type: application/vnd.kafka.v2+json'
```

Cheers
Mark

**Comment by cnwme** [comment] 2020-08-01 13:18
Hi @MarkC0x,
Thank you @MarkC0x, I've 2 topics and i've mixed logs sorry about this mismatch. Here is more infomration avoir my infra AWS; in my use case i have 1 kafka-rest proxy and 1 cluster kafka / Zkp 3 nods each one.
i've double check commands and all it's ok and the result is the same; 1st call GET /records return empty and 2nd return data.

curl --location --request POST 'http://localhost:8082/consumers/DEBUG/' --header 'Content-Type: application/vnd.kafka.v2+json' --data-raw '{"name": "kafka","format": "json","auto.offset.reset": "earliest","auto.commit.enable": "true"}'

**LOG:**
`[2020-08-01 12:29:13,380] INFO ConsumerConfig values:
        allow.auto.create.topics = true
        auto.commit.interval.ms = 5000
        auto.offset.reset = earliest
        bootstrap.servers = [PLAINTEXT://kafka1:9092, kafka2:9092, kafka3:9092]
        check.crcs = true
        client.dns.lookup = default
        client.id =
        client.rack =
        connections.max.idle.ms = 540000
        default.api.timeout.ms = 60000
        enable.auto.commit = true
        exclude.internal.topics = true
        fetch.max.bytes = 52428800
        fetch.max.wait.ms = 500
        fetch.min.bytes = 1
        group.id = DEBUG
        group.instance.id = null
        heartbeat.interval.ms = 3000
        interceptor.classes = []
        internal.leave.group.on.close = true
        isolation.level = read_uncommitted
        key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
        max.partition.fetch.bytes = 1048576
        max.poll.interval.ms = 300000
        max.poll.records = 30
        metadata.max.age.ms = 300000
        metric.reporters = []
        metrics.num.samples = 2
        metrics.recording.level = INFO
        metrics.sample.window.ms = 30000
        partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
        receive.buffer.bytes = 65536
        reconnect.backoff.max.ms = 1000
        reconnect.backoff.ms = 50
        request.timeout.ms = 30000
        retry.backoff.ms = 100
        sasl.client.callback.handler.class = null
        sasl.jaas.config = null
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        sasl.kerberos.ticket.renew.window.factor = 0.8
        sasl.login.callback.handler.class = null
        sasl.login.class = null
        sasl.login.refresh.buffer.seconds = 300
        sasl.login.refresh.min.period.seconds = 60
        sasl.login.refresh.window.factor = 0.8
        sasl.login.refresh.window.jitter = 0.05
        sasl.mechanism = GSSAPI
        security.protocol = PLAINTEXT
        security.providers = null
        send.buffer.bytes = 131072
        session.timeout.ms = 10000
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        ssl.endpoint.identification.algorithm = https
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLS
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS
        value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
 (org.apache.kafka.clients.consumer.ConsumerConfig)
[2020-08-01 12:29:13,381] WARN The configuration 'threads' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
[2020-08-01 12:29:13,381] WARN The configuration 'instance.timeout.ms' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
[2020-08-01 12:29:13,382] WARN The configuration 'schema.registry.url' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
[2020-08-01 12:29:13,382] WARN The configuration 'request.max.bytes' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
[2020-08-01 12:29:13,382] INFO Kafka version: 5.4.2-ccs (org.apache.kafka.common.utils.AppInfoParser)
[2020-08-01 12:29:13,382] INFO Kafka commitId: e3a41889676b904d (org.apache.kafka.common.utils.AppInfoParser)
[2020-08-01 12:29:13,382] INFO Kafka startTimeMs: 1596284953382 (org.apache.kafka.common.utils.AppInfoParser)
[2020-08-01 12:29:13,383] INFO KafkaRestConfig values:
        access.control.allow.headers =
        access.control.allow.methods =
        access.control.allow.origin =
        authentication.method = NONE
        authentication.realm =
        authentication.roles = [*]
        authentication.skip.paths = []
        bootstrap.servers = PLAINTEXT://kafka1:9092,kafka2:9092,kafka3:9092
        client.init.timeout.ms = 60000
        client.sasl.kerberos.kinit.cmd = /usr/bin/kinit
        client.sasl.kerberos.min.time.before.relogin = 60000
        client.sasl.kerberos.service.name =
        client.sasl.kerberos.ticket.renew.jitter = 0.05
        client.sasl.kerberos.ticket.renew.window.factor = 0.8
        client.sasl.mechanism = GSSAPI
        client.security.protocol = PLAINTEXT
        client.ssl.cipher.suites =
        client.ssl.enabled.protocols = TLSv1.2,TLSv1.1,TLSv1
        client.ssl.endpoint.identification.algorithm =
        client.ssl.key.password = [hidden]
        client.ssl.keymanager.algorithm = SunX509
        client.ssl.keystore.location =
        client.ssl.keystore.password = [hidden]
        client.ssl.keystore.type = JKS
        client.ssl.protocol = TLS
        client.ssl.provider =
        client.ssl.trustmanager.algorithm = PKIX
        client.ssl.truststore.location =
        client.ssl.truststore.password = [hidden]
        client.ssl.truststore.type = JKS
        client.timeout.ms = 500
        client.zk.session.timeout.ms = 30000
        compression.enable = true
        consumer.instance.timeout.ms = 2137483646
        consumer.iterator.backoff.ms = 50
        consumer.iterator.timeout.ms = 1
        consumer.request.max.bytes = 26000000
        consumer.request.timeout.ms = 125
        consumer.threads = 1020
        debug = false
        fetch.min.bytes = 1
        host.name =
        id = proxy-1
        idle.timeout.ms = 30000
        kafka.rest.resource.extension.class = []
        listeners = []
        metric.reporters = []
        metrics.jmx.prefix = kafka.rest
        metrics.num.samples = 2
        metrics.sample.window.ms = 30000
        metrics.tag.map = []
        port = 8082
        producer.threads = 520
        request.logger.name = io.confluent.rest-utils.requests
        resource.extension.classes = []
        response.mediatype.default = application/vnd.kafka.v1+json
        response.mediatype.preferred = [application/vnd.kafka.v1+json, application/vnd.kafka+json, application/json]
        rest.servlet.initializor.classes = []
        schema.registry.url = http://localhost:8081
        shutdown.graceful.ms = 5000
        simpleconsumer.pool.size.max = 0
        simpleconsumer.pool.timeout.ms = 1000
        ssl.cipher.suites = []
        ssl.client.auth = false
        ssl.client.authentication = NONE
        ssl.enabled.protocols = []
        ssl.endpoint.identification.algorithm = null
        ssl.key.password = [hidden]
        ssl.keymanager.algorithm =
        ssl.keystore.location =
        ssl.keystore.password = [hidden]
        ssl.keystore.type = JKS
        ssl.protocol = TLS
        ssl.provider =
        ssl.trustmanager.algorithm =
        ssl.truststore.location =
        ssl.truststore.password = [hidden]
        ssl.truststore.type = JKS
        websocket.path.prefix = /ws
        websocket.servlet.initializor.classes = []
        zookeeper.connect = zkp1:2181,zkp2:2181,zkp3:2181/kafka
 (io.confluent.kafkarest.KafkaRestConfig)
[2020-08-01 12:29:13,388] INFO 127.0.0.1 - - [01/Aug/2020:12:29:13 +0000] "POST /consumers/DEBUG HTTP/1.1" 200 90  9 (io.confluent.rest-utils.requests)
`

curl --location --request POST 'http://localhost:8082/consumers/DEBUG/instances/kafka/subscription' --header 'Content-Type: application/vnd.kafka.v2+json' --data-raw '{"topics": ["topic1"]}'

**LOG**:
`[2020-08-01 12:31:01,681] INFO [Consumer clientId=consumer-DEBUG-408660, groupId=DEBUG] Subscribed to topic(s): topic1 (org.apache.kafka.clients.consumer.KafkaConsumer)
[2020-08-01 12:31:01,682] INFO 127.0.0.1 - - [01/Aug/2020:12:31:01 +0000] "POST /consumers/DEBUG/instances/kafka/subscription HTTP/1.1" 204 0  1 (io.confluent.rest-utils.requests)

[2020-08-01 12:31:54,809] INFO [Consumer clientId=consumer-DEBUG-408660, groupId=DEBUG] Cluster ID: z8alwbaLTMGGG-avJit9JQ (org.apache.kafka.clients.Metadata)
[2020-08-01 12:31:54,809] INFO [Consumer clientId=consumer-DEBUG-408660, groupId=DEBUG] Discovered group coordinator kafka1:9092 (id: 2147483646 rack: null) (org.apache.kafka.clients.
consumer.internals.AbstractCoordinator)
[2020-08-01 12:31:54,809] INFO [Consumer clientId=consumer-DEBUG-408660, groupId=DEBUG] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-08-01 12:31:54,810] INFO [Consumer clientId=consumer-DEBUG-408660, groupId=DEBUG] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-08-01 12:31:57,812] INFO [Consumer clientId=consumer-DEBUG-408660, groupId=DEBUG] Finished assignment for group at generation 1: {consumer-DEBUG-408660-62ab1256-011e-4ed1-a5ea-3fc0efae11a1=Assignmen
t(partitions=[topic1-0, topic1-1, topic1-2])} (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2020-08-01 12:31:57,828] INFO [Consumer clientId=consumer-DEBUG-408660, groupId=DEBUG] Successfully joined group with generation 1 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-08-01 12:31:57,829] INFO [Consumer clientId=consumer-DEBUG-408660, groupId=DEBUG] Adding newly assigned partitions: topic1-2, topic1-0, topic1-1 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2020-08-01 12:31:57,832] INFO [Consumer clientId=consumer-DEBUG-408660, groupId=DEBUG] Found no committed offset for partition topic1-2 (org.apache.kafka.clients.consumer.internals.
ConsumerCoordinator)
[2020-08-01 12:31:57,832] INFO [Consumer clientId=consumer-DEBUG-408660, groupId=DEBUG] Found no committed offset for partition topic1-0 (org.apache.kafka.clients.consumer.internals.
ConsumerCoordinator)
[2020-08-01 12:31:57,832] INFO [Consumer clientId=consumer-DEBUG-408660, groupId=DEBUG] Found no committed offset for partition topic1-1 (org.apache.kafka.clients.consumer.internals.
ConsumerCoordinator)`

curl --location --request GET 'http://localhost:8082/consumers/DEBUG/instances/kafka/records' --header 'Accept: application/vnd.kafka.json.v2+json' --header 'Content-Type: application/vnd.kafka.v2+json'

**LOG** 1st GET /records: 
`[2020-08-01 12:31:57,833] INFO 127.0.0.1 - - [01/Aug/2020:12:31:54 +0000] "GET /consumers/DEBUG/instances/kafka/records HTTP/1.1" 200 2  3026 (io.confluent.rest-utils.requests)
[2020-08-01 12:31:58,234] INFO [Consumer clientId=consumer-DEBUG-408660, groupId=DEBUG] Resetting offset for partition topic1-2 to offset 1428626. (org.apache.kafka.clients.consumer.
internals.SubscriptionState)
[2020-08-01 12:31:58,334] INFO [Consumer clientId=consumer-DEBUG-408660, groupId=DEBUG] Resetting offset for partition topic1-0 to offset 1428236. (org.apache.kafka.clients.consumer.
internals.SubscriptionState)
[2020-08-01 12:31:58,334] INFO [Consumer clientId=consumer-DEBUG-408660, groupId=DEBUG] Resetting offset for partition topic1-1 to offset 1427507. (org.apache.kafka.clients.consumer.
internals.SubscriptionState)`


**2nd GET /records : after 5 mins waitting (juste for test)**
`
[2020-08-01 12:46:13,146] INFO 127.0.0.1 - - [01/Aug/2020:12:46:13 +0000] "GET /consumers/DEBUG/instances/kafka/records HTTP/1.1" 200 2  126 (io.confluent.rest-utils.requests)
`

**3rd GET /records : just after the 2nd one :**
`[2020-08-01 12:46:19,675] INFO 127.0.0.1 - - [01/Aug/2020:12:46:19 +0000] "GET /consumers/DEBUG/instances/kafka/records HTTP/1.1" 200 277415  6 (io.confluent.rest-utils.requests)
`


**Here is the configuration of the KAFKA-REST-PROXY instance (EC2 - AWS):**
`id=proxy-1
#schema.registry.url=http://localhost:8081
zookeeper.connect=zkp1:2181,zkp2:2181,zkp3:2181/kafka
bootstrap.servers=PLAINTEXT://kafka1:9092,kafka2:9092,kafka3:9092
producer.threads=520
consumer.threads=1020

# Perf problems
consumer.request.timeout.ms=125
streams.buffer.max.time.ms=125
#metric.reporters=
fetch.min.bytes=1
# problem commit
offset.flush.timeout.ms=5000
# 12.03.2020
consumer.request.max.bytes=26000000
# no limit simpleconsumer
simpleconsumer.pool.size.max=0

offset.retention.minutes=43200
shutdown.graceful.ms=5000

#
# Configure interceptor classes for sending consumer and producer metrics to Confluent Control Center
# Make sure that monitoring-interceptors-<version>.jar is on the Java class path
#consumer.interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
#producer.interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor

# the maximum size of a request in bytes
max.request.size=26000000

#instance keep alive to 24 days instead of 5 minutes
consumer.instance.timeout.ms=2137483646`

** Here is configuration cluster kafka 3 nodes ** sample conf kafka1, for the 2 other nodes, same conf (changing broker id and name):
`broker.id=1
############################# Socket Server Settings #############################

listeners=PLAINTEXT://kafka1:9092

# The number of threads that the server uses for receiving requests from the network and sending responses to the network
# Toomany openfile 24/02/2020
num.network.threads=8
# The number of threads that the server uses for processing requests, which may include disk I/O
num.io.threads=8
# The send buffer (SO_SNDBUF) used by the socket server
socket.send.buffer.bytes = 102400
# The receive buffer (SO_RCVBUF) used by the socket server
socket.receive.buffer.bytes = 102400
# The maximum size of a request that the socket server will accept (protection against OOM)
socket.request.max.bytes = 104857600
# Compress data
compression.type=lz4
#increasing hte max size of a message ISO SOA 20Mo
max.request.size = 26000000
message.max.bytes = 26000000
fetch.message.max.bytes = 26000000
replica.fetch.max.bytes = 26000000
############################# Log Basics #############################
log.dirs=/data/kafka
num.partitions=3
min.insync.replicas=2
num.recovery.threads.per.data.dir=1
############################# Internal Topic Settings  #############################
offsets.topic.replication.factor=3
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
offsets.topic.num.partitions=30
# 7 days offset retention
offsets.retention.minutes=20160
# 24 days to expiration
transactional.id.expiration.ms=2147483647
############################# Log Retention Policy #############################
# The minimum age of a log file to be eligible for deletion due to age
log.retention.hours=336
log.segment.bytes=1073741824
log.retention.check.interval.ms=300000
############################# Zookeeper #############################
zookeeper.connect=zkp1:2181,zkp2:2181,zkp3:2181/kafka
# Timeout in ms for connecting to zookeeper
zookeeper.connection.timeout.ms=16000
zookeeper.session.timeout.ms=16000
##################### Confluent Proactive Support #####################
confluent.support.metrics.enable=false
confluent.support.customer.id=anonymous
############################# Group Coordinator Settings #############################

group.initial.rebalance.delay.ms=3000
max.poll.interval.ms=30000
group.min.session.timeout.ms=10000
group.max.session.timeout.ms=600000

delete.topic.enable=true
auto.create.topics.enable=false

#Authentification SSL
allow.everyone.if.no.acl.found=true
security.inter.broker.protocol=PLAINTEXT

inter.broker.protocol.version=0.11.0
log.message.format.version=0.11.0`

Hope that helps to more comprehensions about issue.

Regards 
Martin.

**Comment by MarkC0x** [comment] 2020-08-01 20:51
Hi @cnwme,

Thank you for providing all those details, that helps.

I can see that in your REST Proxy configuration file you have an extremely low value set for `consumer.request.timeout.ms` (which is set to `125ms`).  I would suggest either, removing that configuration line entirely from your file, so that it defaults to the `1000ms`, or better still -- since you are running REST Proxy on AWS -- setting it to something like the following:

```
consumer.request.timeout.ms=5000
```

What I believe is happening, is that your consumer request is timing out before processing the records responses from REST Proxy.  However, sometimes it will get through, depending on network and other factors, etc.

I could recreate similar behavior to what you were seeing by using an aggressively low consumer timeout value.

Cheers
Mark

**Comment by cnwme** [comment] 2020-08-01 21:32
hi @MarkC0x,
yes you Right 👍 
with 5000 it works well.
but, way we don't get timeout on log ?
Regards 
Martin

**Comment by MarkC0x** [comment] 2020-08-02 05:02
Hi @cnwme,

Excellent -- I am glad that worked!

You probably wouldn't see a timeout message under default logging levels, since the consumer was doing exactly what you asked it to do (and there was no error or abnormal situation).  But you may get some indication if you switch to `DEBUG` or `TRACE` logging levels (but not sure as I have not explicitly tried that in this situation).

Cheers
Mark

**Comment by cnwme** [comment] 2020-08-03 08:55
hi @MarkC0x,
it could be suitable to get this timeout log on level WARN, to get it directly on log without debug mode for monitoring. 
Regards
Martin

**Closed** 2020-08-07 10:42 UTC
