### ISSUE TITLE
Multiple consumers for a single topic fail for rest-proxy starting with branch 6.0.1-post

### ISSUE THREAD

**Issue by sbange-reply** [confluentinc/kafka-rest#789] opened 2021-01-12 13:35 UTC
We are consuming a single topic with multiple consumers using the rest-proxy, which works fine up to branch 6.0.0-post. Recently we updated to branch 6.0.1-post (or the latest docker hub confluent image) and encountered an error while trying to join additional consumers on a single topic. On join it would give us the (level INFO) message:

`Attempt to heartbeat failed since group is rebalancing (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)`

until the initially joined consumer would timeout and get disposed. Only then the next consumer would be able to join the same topic and read. To replicate the error:

1. clone confluentinc/cp-all-in-one
2. checkout branch 6.0.1-post
3. change to dir cp-all-in-one
4. docker-compose up
5. run the following script
6. check kafka rest-proxy logs and script output

```bash
#!/bin/bash
# get cluster id for all subsequent operations
KAFKA_CLUSTER_ID=$(docker-compose exec rest-proxy curl -X GET "http://localhost:8082/v3/clusters/" | jq -r ".data[0].cluster_id")
echo "... deleting test topic"
docker-compose exec rest-proxy curl -X DELETE -H "Content-Type: application/json" -d "{\"topic_name\":\"test-topic\",\"partitions_count\":3,\"replication_factor\":1,\"configs\":[]}" "http://localhost:8082/v3/clusters/${KAFKA_CLUSTER_ID}/topics/test-topic" | jq '.'
echo "... creating test topic"
docker-compose exec rest-proxy curl -X POST -H "Content-Type: application/json" -d "{\"topic_name\":\"test-topic\",\"partitions_count\":3,\"replication_factor\":1,\"configs\":[]}" "http://localhost:8082/v3/clusters/${KAFKA_CLUSTER_ID}/topics" | jq '.'
echo "...  producing a single message to every of the three partitions"
docker-compose exec rest-proxy curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json" -H "Accept: application/vnd.kafka.v2+json" --data '{"records":[{"key":"alice","value":{"count":0}},{"key":"alice","value":{"count":1}},{"key":"alice","value":{"count":2}}]}' "http://localhost:8082/topics/test-topic" | jq '.'
docker-compose exec rest-proxy curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json" -H "Accept: application/vnd.kafka.v2+json" --data '{"records":[{"key":"bob","value":{"count":0}},{"key":"bob","value":{"count":1}},{"key":"bob","value":{"count":2}}]}' "http://localhost:8082/topics/test-topic" | jq '.'
docker-compose exec rest-proxy curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json" -H "Accept: application/vnd.kafka.v2+json" --data '{"records":[{"key":"jack","value":{"count":0}},{"key":"jack","value":{"count":1}},{"key":"jack","value":{"count":2}}]}' "http://localhost:8082/topics/test-topic" | jq '.'
echo "... creating consumer 1"
docker-compose exec rest-proxy curl -X POST -H "Content-Type: application/vnd.kafka.v2+json" --data '{"name": "consumer-1", "format": "json", "auto.offset.reset": "earliest", "consumer.request.timeout.ms": "100"}' http://localhost:8082/consumers/consumer-group-1 | jq '.'
echo "... creating consumer 2"
docker-compose exec rest-proxy curl -X POST -H "Content-Type: application/vnd.kafka.v2+json" --data '{"name": "consumer-2", "format": "json", "auto.offset.reset": "earliest", "consumer.request.timeout.ms": "100"}' http://localhost:8082/consumers/consumer-group-1 | jq '.'
echo "... subscribing consumer 1 to test topic"
docker-compose exec rest-proxy curl -X POST -H "Content-Type: application/vnd.kafka.v2+json" --data '{"topics":["test-topic"]}' http://localhost:8082/consumers/consumer-group-1/instances/consumer-1/subscription | jq '.'
echo "... subscribing consumer 2 to test topic"
docker-compose exec rest-proxy curl -X POST -H "Content-Type: application/vnd.kafka.v2+json" --data '{"topics":["test-topic"]}' http://localhost:8082/consumers/consumer-group-1/instances/consumer-2/subscription | jq '.'
echo "starting consumer 1 ..."
while true
do
  echo "... reading with consumer 1"
  docker-compose exec -T rest-proxy curl -X GET -H "Accept: application/vnd.kafka.json.v2+json" http://localhost:8082/consumers/consumer-group-1/instances/consumer-1/records?timeout=200
  sleep 2
done &
echo "starting consumer 2 ..."
while true
do
  echo "... reading with consumer 2"
  docker-compose exec -T rest-proxy curl -X GET -H "Accept: application/vnd.kafka.json.v2+json" http://localhost:8082/consumers/consumer-group-1/instances/consumer-2/records?timeout=200
  sleep 2
done &
```

If you repeat the steps but checkout branch 6.0.0-post no error will occur, consumers will join and read (stop the formerly started background script before, of course...).

**Comment by MrR0807** [comment] 2021-08-18 14:07
Is this still an issue? Because I'm running Kafka-Rest with 7.1.0 version and I'm not getting this error.

**Comment by ehumber** [comment] 2022-04-14 11:20
This should be fixed by https://github.com/confluentinc/kafka-rest/pull/942, which has been merged into all release branches.

Closing the issue, @sbange-reply please reopen if you still see the problem

@MrR0807 Yes, it was still a problem in 7.1.0, I could reproduce consistently against the master branch.

**Closed by ehumber** 2022-04-14 11:20 UTC

**Comment by sbange-reply** [comment] 2022-04-14 11:40
Thanks a lot @ehumber !
